### ISSUE TITLE
Then lengths of dataset and comet file do not match.

### ISSUE THREAD

**Issue by Tebmer** [morecry/MISC#2]
Hi,

When I run your code to train model, it reports an error at the line `assert len(df) == len(comet) == len(comet_st)`, and I find that their lengths are not the same (e.g. for test dataset, one is 1764, the other is 1365). So, how can I solve this problem. Thanks a lot! 
![image](https://user-images.githubusercontent.com/37136730/176372605-b5da6d2c-8dfa-428f-8a02-38ff09eecd31.png)
![image](https://user-images.githubusercontent.com/37136730/176372677-e39acf4d-9b3c-487e-9666-48c17cb4dd52.png)

**Comment by qu574** [comment]
have you solved this problem? I found the same problem

**Comment by Tebmer** [comment]
> have you solved this problem? I found the same problem

Nope..

**Comment by Tebmer** [comment]
I solve this problem by arranging the source code and rerunning `reformat_data.py`, `comet_input_preprocess.py`, `comet_inference.py`, `getComet.py` to generate the comet file.
